import './globals.css'

export const metadata = {
  title: 'Trello Clone',
  description: 'Generated by VB',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>{children}</body>
    </html>
  )
}
